# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'GoogleSignIn'
  pod 'FLAnimatedImage'
  # Pods for Example

end

target 'LitOAuthPKPSignUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'


  # Pods for LitOAuthPKPSignUp

end

target 'LitProtocolSwiftSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LitProtocolSwiftSDK

  target 'LitProtocolSwiftSDKTests' do
    # Pods for testing
  end

end
