# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def litSDKDependency
  pod "PromiseKit", "~> 6.8"
  pod 'TweetNacl', '~> 1.0.0'
#  pod 'web3.swift', :path => "../../Fork/web3.swift/"
  pod 'web3.swift', :git => "git@github.com:LevenWin/web3.swift-1.git", :commit => "d40d4e51e6f1a1e80dc69902e2acba11841e2e9b"

#  pod 'web3swift'
end

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  litSDKDependency

  pod 'SnapKit', '~> 5.6.0'
  pod 'GoogleSignIn', '~> 7.0.0'
  pod 'FLAnimatedImage', '~> 1.0.0'
  pod 'NVActivityIndicatorView'
  pod 'HandyJSON', '~> 5.0.2'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SwifterSwift'
  pod 'JKCategories'
end

target 'LitOAuthPKPSignUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.6.0'
  pod 'Kingfisher', '6.3.1'


  # Pods for LitOAuthPKPSignUp

end

target 'LitProtocolSwiftSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  litSDKDependency
  target 'LitProtocolSwiftSDKTests' do
    # Pods for testing
  end
end



